services:
  app:
    build:
      args:
        user: amaro
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: amaro_image
    container_name: amaro_container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - amaro_net
  nginx:
    image: nginx:alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - amaro_net
networks:
  amaro_net:
    driver: bridge
